### ISSUE TITLE
ErrorException [ Notice ]: Undefined index: t

### ISSUE THREAD

**Issue by codeho** [hamlphp/HamlPHP#10]
Hi,
I'm getting the following error:

ErrorException [ Notice ]: Undefined index: t

as soon as i add any element but regular text past body in my haml template.

basically
!!! 5
%html
  %head
    %meta(http-equiv = 'Content-Type' content = 'text/html' charset = 'iso-8859-1')
    %meta(name = 'robots' content = 'noindex')
    %title= $content->title
    - if(isset($styles))
      - foreach ($styles as $file => $type) echo HTML::style($file, array('media' => $type)), "\n"; 
  %body

is fine,

but 
!!! 5
%html
  %head
    %meta(http-equiv = 'Content-Type' content = 'text/html' charset = 'iso-8859-1')
    %meta(name = 'robots' content = 'noindex')
    %title= $content->title
    - if(isset($styles))
      - foreach ($styles as $file => $type) echo HTML::style($file, array('media' => $type)), "\n"; 
  %body
    #hello

throws the error.
on the other hand:

!!! 5
%html
  %head
    %meta(http-equiv = 'Content-Type' content = 'text/html' charset = 'iso-8859-1')
    %meta(name = 'robots' content = 'noindex')
    %title= $content->title
    - if(isset($styles))
      - foreach ($styles as $file => $type) echo HTML::style($file, array('media' => $type)), "\n"; 
  %body
    asdlkjasldkasdla

does not throw an error.

any idea?

here's the rest of the exception:

MODPATH/kohana3-haml/vendor/HamlPHP/src/HamlPHP/Element.php [ 182 ]

177 
178     private function _containsPhpAttribute(array $att_arr)
179     {
180       foreach ($att_arr as $att)
181         {
182             if ($att['t'] == 'php' || $att['t'] == 'function')
183                 return true;
184         }
185  
186         return false;
187     }

any help is greatly appreciated.

**Comment by codeho** [comment]
seems like the indentation has been broken by the form here, just to make sure, i have correct indentation using two spaces
in my template.

**Comment by sniemela** [comment]
Hello,

I tried to reproduce that error but I couldn't. I had error_reporting set to `E_ALL | E_STRICT` in my php.ini.

Could you try this code if it works:

```
!!! 5
%html
  %head
    %meta(http-equiv = 'Content-Type' content = 'text/html' charset = 'iso-8859-1')
    %meta(name = 'robots' content = 'noindex')
    %title $content->title
    - if(isset($styles))
      - foreach ($styles as $file => $type)
        = HTML::style($file, array('media' => $type)) . "\n"
%body
  #hello
```

**Comment by codeho** [comment]
tried that. still throwing the error.

**Comment by codeho** [comment]
hm so this issue is still going on. 
i figured that if i do this it works:

``` html
!!! 5
%html
  %head
  %body
    %content= 
      $content
    %footer
      asdasd

but


!!! 5
%html
  %head
  %body
    %content= 
      $content
    #footer
      asdasd

Does not.
as soon as i create a tag by its id with the hash, it'll bail.

Here's the dump of $att from within _containsPhpAttribute line 177 in Element.php:

array(1) (
    0 => array(2) (
        "t" => string(3) "str"
        "v" => string(6) "footer"
    )
)
```

**Comment by sniemela** [comment]
OK, I forgot to update this branch :) I picked few commits from the official branch which apparently fixed this problem. I recommend to use our official branch which is on https://github.com/hamlphp/HamlPHP.

Did it work?

**Comment by codeho** [comment]
ahh. yep. that worked! thanks :)
