### ISSUE TITLE
HamlPHP renders wrongly indented HTML

### ISSUE THREAD

**Issue by complex64** [hamlphp/HamlPHP#15]
``` haml
- if ($image != null)
  %img{:src => $image}
- else
  Image not found
```

**Should** render to:

``` html
<img src="..."></img>
```

**Instead** it renders to:

``` html
  <img  src="..."></img>
```

The snippet not only bears the original indentation but additionally HamlPHP introduces two white-spaces between the `img` tag and its `src` attribute.

**Comment by svallory** [comment]
Rendered html "beauty" isn't really a big concern. As in most of the time you won't be editing the generated html/php. I'll leave it open though and fix it after finishing other planned features.
