### ISSUE TITLE
_contentEvaluator not set?

### ISSUE THREAD

**Issue by siwilkins** [hamlphp/HamlPHP#18]
Hi there,

Thanks for this HamlPHP - I've returned to PHP from Rails and am relieved to find a good-looking HAML port.

However, I'm afraid I've hit a brick wall with getting it set up...

When I try the demo I get 

```
Fatal error: Call to a member function evaluate() on a non-object in     <blah blah blah>/HamlPHP/HamlPHP.php on line 144
```

It seems to be that the _contentEvaluator attribute doesn't get set - I've had a look around the source and I can't see that it gets set anywhere though?

**Comment by svallory** [comment]
Just confirmed it as a bug. Must have been introduced on the last commits.

**Comment by siwilkins** [comment]
Brilliant - thanks for the fantastically fast response!

**Comment by svallory** [comment]
You are welcome!
