### ISSUE TITLE
HamlPHP renders .class and #id wrong

### ISSUE THREAD

**Issue by aoshiftctrl** [hamlphp/HamlPHP#21]
%article.txt lorem
or
%article{:class => "txt"} 

should render:

```
<article class="txt">lorem</article>
```

in the cached php file

but the currend version renders inside the php file the following syntax

```
<article <?php atts(array('class' => 'txt')); ?>>lorem</article>
```

other attributes like "rel" or "name" and even "style" works fine.

**Comment by svallory** [comment]
This isn't a bug. But can be optimized. Currently, `class` and `id` attributes are always rendered through the `atts` function. In some cases the function is **mandatory** (e.g. when the `class` or `id` is evaluated at runtime) but in the case above it isn't, so it could be optimized.

**Comment by bzerangue** [comment]
I am having the same issue as @aoshiftctrl. Is there a way to get it to work with...

%article.classname

%article#idname

**Comment by aoshiftctrl** [comment]
I mailed several times with svallory, he gave very kind support, but i didn't get i work properly.

**Comment by svallory** [comment]
Can you guys, please, explain to me why it's so important to have this rendering directly to the final HTML?

I'm not saying that it wouldn't be the best option. But a lot of what HamlPHP does relies on rendering to a php file, not an html file. If you have php on your server, the way the page is rendered right now shouldn't be a problem.

**Comment by bzerangue** [comment]
@svallory - i am using [your example](https://github.com/hamlphp/HamlPHP/wiki/Using-HamlPHP) with a php file (index.php) and when it renders it doesn't render as html (as the page should)... it renders with php printed on the page. 

**So the output looks like this...**

'container')); ?>>
'navigation')); ?>>
Etusivu
Tuotteet
Tuotteet

'products')); ?>>

**Then when you view source, it shows the following...**

```
<!DOCTYPE html>
<html>
  <body>
      <div <?php atts(array('id' => 'container')); ?>></div>
      <ul <?php atts(array('class' => 'navigation')); ?>>
        <li>Etusivu</li>
        <li>Tuotteet</li>
      </ul>
      <h2>
        <ul <?php atts(array('class' => 'products')); ?>></ul>
        <?php for ($i = 0; $i < 10; $i++): ?>
          <li><?php echo $i * 7 ?></li>
        <?php endfor; ?>
      </h2>
  </body>
</html>
```

It's like **the PHP is NOT rendering**, it's just printing out the PHP instead of rendering into HTML.

**Comment by svallory** [comment]
Hi, @bzerangue! I've updated the readme to show how to output HTML directly from index.php. Basically, all you need to do is change the last line from

```
echo $content;
```

to

```
echo $parser->evaluate($content);
```

This will output the HTML result the [`HamlPHP::evaluate`](https://github.com/hamlphp/HamlPHP/blob/master/src/HamlPHP/HamlPHP.php#L192) method can also receive a `$contentVariables` `array` so you can pass variables to be used inside your view.

Please, let me know if I can help you with anything else.

**Comment by bzerangue** [comment]
Thank you!!

Do you have partial functionality with this library???

On Feb 21, 2013, at 12:07 PM, Saulo Vallory notifications@github.com
wrote:

Hi, @bzerangue https://github.com/bzerangue! I've updated the readme to
show how to output HTML directly from index.php. Basically, all you need to
do is change the last line from

echo $content;

to

echo $parser->evaluate($content);

This will output the HTML result the HamlPHP::evaluate method can also
receive a $contentVariables array so you can pass variables to be used
inside your view.

Please, let me know if I can help you with anything else.

—
Reply to this email directly or view it on
GitHubhttps://github.com/hamlphp/HamlPHP/issues/21#issuecomment-13903608.

**Comment by svallory** [comment]
Partial functionality isn't in the scope of HamlPHP. It's a language parser, not a view engine. Views and partials are handled differently depending on the framework you are using. There are a couple integrations thought. Check out [Silex-HamlPHP](/hamlphp/Silex-HamlPHP) for [Silex](http://silex.sensiolabs.org/), [Yiihppie](theblacksmith/Yiihppie) for [Yii](http://www.yiiframework.com/) and [wp-hamlphp](/hamlphp/wp-hamlphp) for wordpress. (not sure if the last one even works with the current version of WP)
