### ISSUE TITLE
Class 'Interpolation' not found

### ISSUE THREAD

**Issue by matify** [hamlphp/HamlPHP#5]
"PHP Fatal error:  Class 'Interpolation' not found in /Users/Mat/Sites/Slip/src/HamlPHP/DoctypeNode.php on line 21"

Was using a version from over a week ago and saw that some updates had been pushed; was met with this error. Tried to see if I could fix it myself but the framework I was using kept giving me an error message of "Uninitialized string offset: 122".

EDIT // And then I see there were some unread posts about this class in particular, so not sure if it was even up to speed anyhow.

**Comment by sniemela** [comment]
All tests passed. Make sure you have the latest commits. What PHP version are you using?

**Comment by matify** [comment]
PHP 5.3.2

I just tried it again with a fresh clone using the example from the README but still getting HTTP Error 500 with the Fatal error.

**Comment by sniemela** [comment]
Update your code. svallory added the missing line to the DoctypeNode class.

**Comment by matify** [comment]
Updated, that fixed the fatal error. 
It's just left the uninitialized string offset notice, but I'll make a pull request or something of the like with the fix for that.
